name: Nightly
on: 
  push:
    branches:
    - master
jobs:
  build:
    name: Build nuget
    runs-on: windows-2025
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Prepare Env
      uses: microsoft/setup-msbuild@v2
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
    - name: Build native
      run: |
        vcpkg integrate install
        MSBuild -nologo -v:minimal MrmPatcher.Native\MrmPatcher.Native.vcxproj /p:Configuration=Release /p:Platform=x64
        MSBuild -nologo -v:minimal MrmPatcher.Native\MrmPatcher.Native.vcxproj /p:Configuration=Release /p:Platform=ARM64
    - name: Publish nuget
      run: |
        dotnet pack MrmPatcher\MrmPatcher.csproj --configuration Release -p:ContinuousIntegrationBuild=true -p:Deterministic=true
        dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.actor }}/index.json"
        dotnet nuget push "$(Get-ChildItem MrmPatcher\bin\Release\*.nupkg)" -k ${{ secrets.GITHUB_TOKEN }} -s "github"
        dotnet nuget push "$(Get-ChildItem MrmPatcher\bin\Release\*.nupkg)" -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
    - name: Upload nuget
      uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: |
          MrmPatcher/bin/Release/*.nupkg
          MrmPatcher/bin/Release/*.snupkg
